# Generated by Django 2.0.5 on 2018-06-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backpack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateperson',
            name='facebook_url',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='privateperson',
            name='parent_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='privateperson',
            name='parent_facebook_url',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='privateperson',
            name='parent_phone',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='privateperson',
            name='address',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='privateperson',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='privateperson',
            name='phone',
            field=models.CharField(default='+40 ...', max_length=32),
        ),
    ]
